language: rust
script:
  - (cargo install mdbook --git https://github.com/azerupi/mdBook.git --force || true)
  - ./generate-book.sh
  - mv book/* .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
