language: rust
branches:
  only:
    - master

script:
  - (cargo install mdbook --vers '^0.2.0' --force || true)
  - ./generate-book.sh

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
